//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazka
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime DataWydania { get; set; }
        public decimal Cena { get; set; }
        public string Autor { get; set; }
        public string Wydawnictwo { get; set; }
        public bool Audiobook { get; set; }
        public bool Ebook { get; set; }
    }
}
